export const IPC_CHANNELS = {
  handshake: 'contract:handshake',
  appGetVersion: 'app:get-version',
  appGetRuntimeVersions: 'app:get-runtime-versions',
  authSignIn: 'auth:sign-in',
  authSignOut: 'auth:sign-out',
  authGetSessionSummary: 'auth:get-session-summary',
  authGetTokenDiagnostics: 'auth:get-token-diagnostics',
  dialogOpenFile: 'dialog:open-file',
  fsReadTextFile: 'fs:read-text-file',
  storageSetItem: 'storage:set-item',
  storageGetItem: 'storage:get-item',
  storageDeleteItem: 'storage:delete-item',
  storageClearDomain: 'storage:clear-domain',
  apiInvoke: 'api:invoke',
  apiGetOperationDiagnostics: 'api:get-operation-diagnostics',
  updatesCheck: 'updates:check',
  updatesApplyDemoPatch: 'updates:apply-demo-patch',
  pythonProbe: 'python:probe',
  pythonInspectPdf: 'python:inspect-pdf',
  pythonStop: 'python:stop',
  telemetryTrack: 'telemetry:track',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
